FROM python:3.7

# Mecab インストール
RUN apt-get update \
    && apt-get install -y mecab \
    && apt-get install -y libmecab-dev \
    && apt-get install -y mecab-ipadic-utf8\
    && apt-get install -y git\
    && apt-get install -y make\
    && apt-get install -y curl\
    && apt-get install -y xz-utils\
    && apt-get install -y file\
    && apt-get install -y sudo\
    && apt-get install -y wget

RUN git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git\
    && cd mecab-ipadic-neologd\
    && bin/install-mecab-ipadic-neologd -n -y

# Django
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE back.settings_prod
ENV APP_PATH /app

COPY . $APP_PATH/
WORKDIR $APP_PATH
RUN pip install -r requirements/prod.txt
RUN python manage.py collectstatic --noinput