FROM python:3.7

ENV PYTHONUNBUFFERED 1

ENV APP_PATH /apps

# COPY ./server /server
COPY . APP_PATH

WORKDIR $APP_PATH

RUN pip install -r requirements/prod.txt

RUN python manage.py collectstatic --noinput